### ISSUE TITLE
安装不了 

### ISSUE THREAD

**Issue by liyuhbs** [geek-prince/react-native-page-listview#1]
npm install react-native-page-listview --save
 network request to http://10.168.66.124:8085/react-native-page-listview failed, reason: connect ETIMEDOUT 10.168.66.124:8085
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by geek-prince** [comment]
根据报错来看,应该是你的网络超时,网络设置的问题.如果你用了代理服务器的话,可以先关闭代理服务器后试试
