### ISSUE TITLE
怎么点击某一个按钮，使该组件产生下拉效果，并刷新数据？

### ISSUE THREAD

**Issue by sundayha** [geek-prince/react-native-page-listview#18]
例如头条点击底部导航首页按钮时，产生的效果。

**Comment by geek-prince** [comment]
点击某一个按钮后刷新的话,可以使用"手动刷新数据"的方法.`this.PL.manualRefresh(res);`(PL是PageListView的ref引用,README中有提到).但是不能同时使组件产生下拉效果,下拉效果还是得手动下拉触发.

**Comment by sundayha** [comment]
@geek-prince 好的多谢，那请问`RN`中有别的组件能做成像头条那样，点击按钮后，自动下拉动画刷新数据吗？

**Comment by geek-prince** [comment]
应该没有吧,这种特殊的需求一般都要自己写的

**Comment by sundayha** [comment]
@geek-prince ok 多谢

**Comment by sundayha** [comment]
![](https://github.com/sundayha/imageForBlog/blob/master/home/7.gif?raw=true)
搞定了

**Comment by geek-prince** [comment]
不错,搞定了就好
