### ISSUE TITLE
使用 onScroll 属性时无效

### ISSUE THREAD

**Issue by sundayha** [geek-prince/react-native-page-listview#19]
怎么在，`PageListView` 中使用 `onScroll`属性啊？这么写，没有调用 `handleScroll` 方法
```
  handleScroll=(e)=>{
    console.log(e);
  };

<PageListView
          ......
          onScroll={this.handleScroll}
          ......
/>
```

**Comment by geek-prince** [comment]
因为在组件内部用到了scrollEnabled,onScroll这两个属性来判定ListView/FlatList的滚动状态,来实现下拉刷新.所以给PageListView传onScroll属性的话会被组件内的onScroll属性覆盖,本来也想要不要把传给PageListView的onScroll属性方法和组件内的onScroll方法一起执行,但是想着可能两个方法在某些时候会冲突就没有加.你这边具体要用onScroll方法做什么操作呢?你也可以直接在组件源码中进行修改,添加.

**Comment by sundayha** [comment]
@geek-prince 哦哦，我是想在下滚到一定高度时，动态改变导航`header`的标题。类似于头条那样

**Comment by geek-prince** [comment]
哦,这样啊,那你先直接在组件中的onScroll方法中加一下吧

**Comment by sundayha** [comment]
@geek-prince ok 只能这样了，多谢
