### ISSUE TITLE
在Android手机上超级卡，，，，，，，

### ISSUE THREAD

**Issue by kekegdsz** [geek-prince/react-native-page-listview#2]
在Android手机上超级卡，，，，，，，

**Comment by geek-prince** [comment]
你使用的是安卓手机呢还是安卓模拟器呢?如果你在Mac上同时打开iOS模拟器和安卓模拟器的话,有可能会出现卡顿;如果用的是真机的话,如果配置不是特别低的话,也应该不会出现卡顿.你能说一下你使用设备和使用插件的具体情况吗?

**Comment by kekegdsz** [comment]
一加3t

**Comment by geek-prince** [comment]
你具体使用组件时的该组件部分的代码能提供一下吗?
