### ISSUE TITLE
怎么点击某一个按钮，刷新数据？

### ISSUE THREAD

**Issue by BobbySir** [geek-prince/react-native-page-listview#22]
this.PL 这个PL从哪里来？
调用的时候需要的res又是从哪里来？
![image](https://user-images.githubusercontent.com/17491400/58048045-50024d00-7b7c-11e9-91fd-8c5a84636f2d.png)
![image](https://user-images.githubusercontent.com/17491400/58048079-66100d80-7b7c-11e9-9e29-f013be8e47f1.png)

**Comment by geek-prince** [comment]
PL是通过ref获得PageListView的引用,指的是PageListView的这个组件实例.
调用时的res是你传入的要展示的数据的数组.

```js
<PageListView 
	//其他的属性...
	ref={(r)=>{!this.PL&&(this.PL=r)}}
/>
```

代码中应该用"ref",文档中写的"refs"可能是当时写错了

**Comment by BobbySir** [comment]
> PL是通过参考文献获得PageListView的引用，指的是PageListView的这个组件实例。
> 调用时的解析度是你传入的要展示的数据的数组。
> 
> ```js
> < PageListView 
> 	 //其他的属性... 
> 	ref = {（r）=> { ！这个。PL &&（此。PL = R）}}
>  / >
> ```
> 
> 代码中应该用 “裁判”，文档中写的 “裁判” 可能是当时写错了

意思是pl是PageListView这个组件实例，调用this.PL.manualRefresh(res);   这个函数的res参数，其实是我自己重新请求到的数据集，填充到res里面吗？

**Comment by geek-prince** [comment]
对的,就是这样

**Comment by BobbySir** [comment]
1: 这样感觉有点多此一举了，因为我只想调用下拉刷新函数，重新加载一遍数据，但是你却让我自己另外写一个方法去请求服务器数据，并传入手动刷新函数里面。
2:那我不如直接调用refresh=(callBack) 函数， 将callBack保存到 this.state 当中，刷新的时候直接调用refresh=(callBack)函数， 将this.state.callBack传入到refresh函数当中。
代码如下：
   constructor(props){
        super(props);
        this.state ={
            callBack: null,
  }
 
   //处理"下拉刷新"或"一开始加载数据"的方法
    refresh=(callBack)=>{
        this.setState({callBack: callBack});
   }

//点击调用的函数
clickRefresh(){
   this.refresh(this.state.callBack)
}

**Comment by BobbySir** [comment]
> 对的,就是这样

还有这个手动调用刷新没有下拉效果，是有点遗憾， 能否手动调用刷新的时候，模仿用户下拉手指的距离，触发下拉动作并刷新数据？

**Comment by geek-prince** [comment]
因为当时加入这个手动刷新的功能的时候,考虑到的就是可能会有和下拉刷新不一样的刷新操作需求,所以如果需要点击按钮的时候刷新的话就需要这样操作.你说的方法你可以先试一下,看看行不行

**Comment by BobbySir** [comment]
> 因为当时加入这个手动刷新的功能的时候,考虑到的就是可能会有和下拉刷新不一样的刷新操作需求,所以如果需要点击按钮的时候刷新的话就需要这样操作.你说的方法你可以先试一下,看看行不行

我试了是可以刷新的， 但是不会触发下拉处理， 因为你是根据距离判断的，如果有时间的话， 希望你可以做一个手动刷新多状态函数， 一种是当前这种需要传入数据，另一种就是我这种不需要传入数据，最好是可以触发下拉事件就完美了， 另外的问题就是那个一开始没数据显示没有更多数据的问题，要修复下。 拜托了。

**Comment by geek-prince** [comment]
> > 因为当时加入这个手动刷新的功能的时候,考虑到的就是可能会有和下拉刷新不一样的刷新操作需求,所以如果需要点击按钮的时候刷新的话就需要这样操作.你说的方法你可以先试一下,看看行不行
> 
> 我试了是可以刷新的， 但是不会触发下拉处理， 因为你是根据距离判断的，如果有时间的话， 希望你可以做一个手动刷新多状态函数， 一种是当前这种需要传入数据，另一种就是我这种不需要传入数据，最好是可以触发下拉事件就完美了， 另外的问题就是那个一开始没数据显示没有更多数据的问题，要修复下。 拜托了。

好的,你提出的建议我都收到了,下次有时间进行版本更新时修复

**Comment by BobbySir** [comment]
> > > 因为当时加入这个手动刷新的功能的时候,考虑到的就是可能会有和下拉刷新不一样的刷新操作需求,所以如果需要点击按钮的时候刷新的话就需要这样操作.你说的方法你可以先试一下,看看行不行
> > 
> > 
> > 我试了是可以刷新的， 但是不会触发下拉处理， 因为你是根据距离判断的，如果有时间的话， 希望你可以做一个手动刷新多状态函数， 一种是当前这种需要传入数据，另一种就是我这种不需要传入数据，最好是可以触发下拉事件就完美了， 另外的问题就是那个一开始没数据显示没有更多数据的问题，要修复下。 拜托了。
> 
> 好的,你提出的建议我都收到了,下次有时间进行版本更新时修复


对了我还发现你一个问题， 就是进入页面的时候，由于是分页，当一页数据不满足全屏的时候，会自动加载下一页数据，有时候会卡住不动，如下图所示:


![加载更多出错](https://user-images.githubusercontent.com/17491400/58091802-23424a00-7bfd-11e9-8270-dd1002fc6273.jpg)

**Comment by geek-prince** [comment]
这个是rn原生的FlatList组件的机制问题了,你分页每一页加载的数据多一些应该就可以了

**Comment by BobbySir** [comment]
好的，非常感谢，我去试试
